### ISSUE TITLE
install nextflow with conda

### ISSUE THREAD

**Issue by tavareshugo** [cambiotraining/bioinformatics-software-pipelines#5]
On the HPC the default `nextflow` recipe fails with the latest java allowed (version 21). 
Instead, I had to force lower version of `openjdk`:

```yaml
name: nextflow
channels: 
  - conda-forge
  - bioconda
dependencies:
  - nextflow==23.10.1
  - openjdk==17.0.11
```

Might be worth adding a note somewhere about this
